name: magnusfly
description: Simple remote variometer app for paraglider towing.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.3
  sensors_plus: ^7.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
